# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SEMESTER6\P-Visual\pv25-finalproject-bikeLockControl\locker.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.central_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.central_layout.setContentsMargins(10, 10, 10, 10)
        self.central_layout.setSpacing(10)
        self.central_layout.setObjectName("central_layout")
        self.top_buttons_layout = QtWidgets.QHBoxLayout()
        self.top_buttons_layout.setObjectName("top_buttons_layout")
        self.btn_tambah_locker = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tambah_locker.setObjectName("btn_tambah_locker")
        self.top_buttons_layout.addWidget(self.btn_tambah_locker)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.top_buttons_layout.addWidget(self.btn_refresh)
        self.central_layout.addLayout(self.top_buttons_layout)
        self.table_lockers = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_lockers.sizePolicy().hasHeightForWidth())
        self.table_lockers.setSizePolicy(sizePolicy)
        self.table_lockers.setMinimumSize(QtCore.QSize(0, 200))
        self.table_lockers.setObjectName("table_lockers")
        self.table_lockers.setColumnCount(0)
        self.table_lockers.setRowCount(0)
        self.central_layout.addWidget(self.table_lockers)
        self.bottom_buttons_layout = QtWidgets.QHBoxLayout()
        self.bottom_buttons_layout.setObjectName("bottom_buttons_layout")
        self.btn_copy_clipboard = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy_clipboard.setObjectName("btn_copy_clipboard")
        self.bottom_buttons_layout.addWidget(self.btn_copy_clipboard)
        self.central_layout.addLayout(self.bottom_buttons_layout)
        self.delete_widget = QtWidgets.QWidget(self.centralwidget)
        self.delete_widget.setObjectName("delete_widget")
        self.delete_layout = QtWidgets.QHBoxLayout(self.delete_widget)
        self.delete_layout.setObjectName("delete_layout")
        self.input_delete_locker_id = QtWidgets.QLineEdit(self.delete_widget)
        self.input_delete_locker_id.setObjectName("input_delete_locker_id")
        self.delete_layout.addWidget(self.input_delete_locker_id)
        self.btn_paste_clipboard = QtWidgets.QPushButton(self.delete_widget)
        self.btn_paste_clipboard.setObjectName("btn_paste_clipboard")
        self.delete_layout.addWidget(self.btn_paste_clipboard)
        self.btn_hapus_locker = QtWidgets.QPushButton(self.delete_widget)
        self.btn_hapus_locker.setObjectName("btn_hapus_locker")
        self.delete_layout.addWidget(self.btn_hapus_locker)
        self.central_layout.addWidget(self.delete_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.help_dock = QtWidgets.QDockWidget(MainWindow)
        self.help_dock.setObjectName("help_dock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dock_layout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.dock_layout.setObjectName("dock_layout")
        self.help_text = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.help_text.setReadOnly(True)
        self.help_text.setObjectName("help_text")
        self.dock_layout.addWidget(self.help_text)
        self.help_dock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.help_dock)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Locker Management System"))
        self.btn_tambah_locker.setText(_translate("MainWindow", "Tambah Locker"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))
        self.btn_copy_clipboard.setText(_translate("MainWindow", "Copy to Clipboard"))
        self.input_delete_locker_id.setPlaceholderText(_translate("MainWindow", "Enter Locker ID to Delete"))
        self.btn_paste_clipboard.setText(_translate("MainWindow", "Paste from Clipboard"))
        self.btn_hapus_locker.setText(_translate("MainWindow", "Hapus Locker"))
        self.help_dock.setWindowTitle(_translate("MainWindow", "Help & Info"))
